name: 'ESLint Check'
description: 'Runs ESLint checks using config from repo'
inputs:
    repo-token:
        description: "Token used to interact with the Github API."
        required: true
    extensions:
        description: "File extensions to lint. Ex: .js,.jsx,.ts,.tsx"
        default: ".js,.jsx,.ts,.tsx"
    files:
        description: "Glob pattern of files to be linted."
        default: "**/*"
    ignore:
        description: "Glob pattern to ignore from linting."
        default: "**/node_modules/**"
    working-directory:
        description: "Directory where eslint should execute."
runs:
    using: 'node12'
    main: 'src/action.js'
branding:
  icon: "check-circle"
  color: "yellow"
