name: 'ESLint Check'
description: 'Runs ESLint checks using config from repo'
inputs:
    repo-token:
        description: 'The GITHUB_TOKEN secret'
        required: true
runs:
    using: 'node12'
    main: 'src/action.js'
